os:
- linux
- osx
language: node_js
node_js:
- '10'
- '8'
install:
- yarn install
- yarn build
- yarn add $WEBPACK $TSLOADER $VUELOADER -D
- yarn lint
env:
- WEBPACK=webpack@^5.0.0-alpha.5 TSLOADER=ts-loader@^5.0.0 VUELOADER=vue-loader@^15.2.4
- WEBPACK=webpack@^4.0.0 TSLOADER=ts-loader@^5.0.0 VUELOADER=vue-loader@^15.2.4
- WEBPACK=webpack@^3.10.0 TSLOADER=ts-loader@^3.4.0 VUELOADER=vue-loader@^13.5.0
- WEBPACK=webpack@^2.7.0 TSLOADER=ts-loader@^3.4.0 VUELOADER=vue-loader@^13.5.0
deploy:
  provider: npm
  email: pmabres@gmail.com
  skip_cleanup: true
  api_key:
    secure: ZwHqpeqlvPghv51hQ/1FUO1dUYz79RvMP8ErG4SNcNiZVbOSWz9gm8tN1sAL4pEg6kLFD1wvXmOEfPR5e+N9cr6+QTSIswrysNJmDoq1L//dn02twQMKHhGkgpH2bkB24pcA9ZreXRNqtWgqyets9tXVkmc40M92HkMqQ9LIbbBT3/+knIUmxvcrI+fFcbocXbUsn4QnqAPswWDM4OlYDB3OAWZaIeiKQ8BiAOdBhXtZQqVfqB8MvTZusWLMv85JJsq6Ipbi7WZJD+2bU+HF/B33BXXXvfHcqqdeVU+6ReI35+t6jcVgHIln1L7EAcM83e24L13i//AA+A9V1gERMCMfXti3Xf3gv/Hs2xaA63bMKNmqaXUrGQZVlyU2g1S/c9U2EzIZ9JipV9HE128XTRiUFmlwQFM+dI5FIeNU1PhDuFudd2fwH9JRB7oCkhq4t0Fg0Mxz0m2102VdfjS69FtxvIj11QznLIB2AW0M2MaP3hVqFIg3kHMNyWXAFE+B+XLev9Og47JCkoj1wrm09CCHwBqQBm4qfHH3HyIOhoPGImb0UzVwVYnNqymItATNoYbnYy45hXu7Gei/vBrLBrsXtgMxsN22XcXjAG8FSeqe9cAL9fqqcizUbqjKQpKrjf+BHTwMGYjqbb7xRvWA+vmuksuTRgy4AGNhqZUebsQ=
  on:
    tags: true
    branch: master
  tag: next
